### ISSUE TITLE
Create Overview

### ISSUE THREAD

**Issue by n2o** [deutscher-pfadfinderbund/dpb#1]
Like this:

```
DPB
|   \
Gau  Gau
|  \ |  \
Ring ... Ring
```

**Comment by MrEbbinghaus** [comment]
Das ist im Adminmenü in Zukunft einsehbar.

Soll das auch öffentlich?

**Comment by n2o** [comment]
Hm weiß nicht. Muss eigentlich nicht öffentlich sein.
