### ISSUE TITLE
Kontaktformular funktioniert nicht

### ISSUE THREAD

**Issue by n2o** [deutscher-pfadfinderbund/dpb#101]
Versucht man eine Mail abzuschicken, scheitert es und wirft einen Stacktrace.

<img width="566" alt="image" src="https://user-images.githubusercontent.com/1507474/174598080-13f15167-acc0-45dc-8932-470d01ed633d.png">

**Comment by MrEbbinghaus** [comment]
![image](https://user-images.githubusercontent.com/2965273/174606895-2288919f-b0d8-49e6-893c-0ad428138c74.png)

Vermutlich wurden in älteren Django Versionen EnvVars mit in die Settings gemerged. 
Das scheint nicht mehr der Fall zu sein, da hier Standard Werte sind.
