### ISSUE TITLE
Suche im Bundesarchiv liefert keine Treffer

### ISSUE THREAD

**Issue by n2o** [deutscher-pfadfinderbund/dpb#105]
Beispielquery: `defense`

https://deutscher-pfadfinderbund.de/bundesarchiv/katalog/?q=defense

Im Archiv gibt es aber Items, die im Titel das Stichwort beinhalten, bspw. `Bund [...] defense)`

<img width="188" alt="image" src="https://user-images.githubusercontent.com/1507474/202026003-12d27df4-62d2-4610-baa6-ca3e1cee3c27.png">

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/1507474/202025760-4d27e750-ed09-4143-8102-35bb0e79cf51.png">

**Comment by MrEbbinghaus** [comment]
Seltsam. Das ist ja nicht mal irgendein Randfall. 

Andere Suchbegriffe:
`Bund xxxxxxxxxx defense)` → fail
`defense)` → fail

Umbenennen des Titels hilft auch nicht 
`Bund xxxxxxxxxxxxxx defense` → fail
`defense xxxxxx defense)` → fail

Zum debuggen sollte man mal den Output von `annotate` aus https://github.com/deutscher-pfadfinderbund/dpb/blob/master/archive/views.py#L64 angucken.
