### ISSUE TITLE
Kalender Anzeige- und Einbindungsmöglichkeiten beschreiben

### ISSUE THREAD

**Issue by n2o** [deutscher-pfadfinderbund/dpb#56]
Im internen Bereich sollte unser Nextcloud Kalender beschrieben werden.

- [x] Link zum öffentlichen Kalender einbinden
- [x] Ggf. Kalender per iFrame einbinden
- [x] Kurzbeschreibung mit Verweise auf Fremdanleitungen, wie man den Kalender abonnieren kann mit gängigen Systemen

**Comment by MrEbbinghaus** [comment]
Closed by https://github.com/deutscher-pfadfinderbund/dpb/commit/df06ebc586f62dcce51188f7db67f37ebba3991b

Mehr Beschreibungen müsste man mit der Zeit hinzufügen
