### ISSUE TITLE
"Digitaler Bund" überarbeiten

### ISSUE THREAD

**Issue by n2o** [deutscher-pfadfinderbund/dpb#88]
Der Kalender sieht irgendwie nicht mehr rund aus und unser Jitsi ist nun weg, das können wir also löschen / archivieren.

**Comment by MrEbbinghaus** [comment]
Kalender ist gefixed in d9019bb203b3959c89ecf83496050e1a316f1394 der hat eine neue Share-ID bekommen (warum auch immer) muss man in Zukunft mal drauf achten. 

Die Seiten für Jitsi und Mattermost sind gar nicht mehr verlinkt, oder? (siehe https://github.com/deutscher-pfadfinderbund/dpb/pull/89 für Archivierungsoptionen)

**Comment by n2o** [comment]
Doch hier: https://deutscher-pfadfinderbund.de/digitaler-bund/

**Comment by n2o** [comment]
Hab die Seiten gelöscht. Das verwirrt, wurde gerade wieder drauf angesprochen.
